import org.drools.demo20220623.model.Message;

rule "Hello World"
when
    m : Message( status == Message.HELLO, message : message )
then
    System.out.println( message );
    modify ( m ) {
        setMessage("Goodbye Z world"),
        setStatus(Message.GOODBYE)
    };
end

rule "Good Bye"
when
    Message( status == Message.GOODBYE, message : message )
then
    System.out.println( message );
end
